In [5]:
from sklearn.feature_extraction.text import TfidfVectorizer

v = TfidfVectorizer()

In [6]:
corpus = [
     "Thor eating pizza, Loki is eating pizza, Ironman ate pizza already",
    "Apple is announcing new iphone tomorrow",
    "Tesla is announcing new model-3 tomorrow",
    "Google is announcing new pixel-6 tomorrow",
    "Microsoft is announcing new surface tomorrow",
    "Amazon is announcing new eco-dot tomorrow",
    "I am eating biryani and you are eating grapes"
]

In [7]:
v.fit(corpus)
v.get_feature_names_out()

array(['already', 'am', 'amazon', 'and', 'announcing', 'apple', 'are',
       'ate', 'biryani', 'dot', 'eating', 'eco', 'google', 'grapes',
       'iphone', 'ironman', 'is', 'loki', 'microsoft', 'model', 'new',
       'pixel', 'pizza', 'surface', 'tesla', 'thor', 'tomorrow', 'you'],
      dtype=object)

In [8]:
v.vocabulary_

{'thor': 25,
 'eating': 10,
 'pizza': 22,
 'loki': 17,
 'is': 16,
 'ironman': 15,
 'ate': 7,
 'already': 0,
 'apple': 5,
 'announcing': 4,
 'new': 20,
 'iphone': 14,
 'tomorrow': 26,
 'tesla': 24,
 'model': 19,
 'google': 12,
 'pixel': 21,
 'microsoft': 18,
 'surface': 23,
 'amazon': 2,
 'eco': 11,
 'dot': 9,
 'am': 1,
 'biryani': 8,
 'and': 3,
 'you': 27,
 'are': 6,
 'grapes': 13}

In [9]:
all_feature_names = v.get_feature_names_out()
idf_scores = {}
for word in all_feature_names:
    i = v.vocabulary_.get(word)
    idf_scores[word] = v.idf_[i]

print(idf_scores.items())

dict_items([('already', np.float64(2.386294361119891)), ('am', np.float64(2.386294361119891)), ('amazon', np.float64(2.386294361119891)), ('and', np.float64(2.386294361119891)), ('announcing', np.float64(1.2876820724517808)), ('apple', np.float64(2.386294361119891)), ('are', np.float64(2.386294361119891)), ('ate', np.float64(2.386294361119891)), ('biryani', np.float64(2.386294361119891)), ('dot', np.float64(2.386294361119891)), ('eating', np.float64(1.9808292530117262)), ('eco', np.float64(2.386294361119891)), ('google', np.float64(2.386294361119891)), ('grapes', np.float64(2.386294361119891)), ('iphone', np.float64(2.386294361119891)), ('ironman', np.float64(2.386294361119891)), ('is', np.float64(1.1335313926245225)), ('loki', np.float64(2.386294361119891)), ('microsoft', np.float64(2.386294361119891)), ('model', np.float64(2.386294361119891)), ('new', np.float64(1.2876820724517808)), ('pixel', np.float64(2.386294361119891)), ('pizza', np.float64(2.386294361119891)), ('surface', np.float64(2.386294361119891)), ('tesla', np.float64(2.386294361119891)), ('thor', np.float64(2.386294361119891)), ('tomorrow', np.float64(1.2876820724517808)), ('you', np.float64(2.386294361119891))])

In [10]:
idf_scores = dict(sorted(idf_scores.items(),key=lambda x:x[1]))
idf_scores

{'is': np.float64(1.1335313926245225),
 'announcing': np.float64(1.2876820724517808),
 'new': np.float64(1.2876820724517808),
 'tomorrow': np.float64(1.2876820724517808),
 'eating': np.float64(1.9808292530117262),
 'already': np.float64(2.386294361119891),
 'am': np.float64(2.386294361119891),
 'amazon': np.float64(2.386294361119891),
 'and': np.float64(2.386294361119891),
 'apple': np.float64(2.386294361119891),
 'are': np.float64(2.386294361119891),
 'ate': np.float64(2.386294361119891),
 'biryani': np.float64(2.386294361119891),
 'dot': np.float64(2.386294361119891),
 'eco': np.float64(2.386294361119891),
 'google': np.float64(2.386294361119891),
 'grapes': np.float64(2.386294361119891),
 'iphone': np.float64(2.386294361119891),
 'ironman': np.float64(2.386294361119891),
 'loki': np.float64(2.386294361119891),
 'microsoft': np.float64(2.386294361119891),
 'model': np.float64(2.386294361119891),
 'pixel': np.float64(2.386294361119891),
 'pizza': np.float64(2.386294361119891),
 'surface': np.float64(2.386294361119891),
 'tesla': np.float64(2.386294361119891),
 'thor': np.float64(2.386294361119891),
 'you': np.float64(2.386294361119891)}

In [11]:
corpus[:2]

['Thor eating pizza, Loki is eating pizza, Ironman ate pizza already',
 'Apple is announcing new iphone tomorrow']

In [12]:
print(v.transform(corpus).toarray()[:2])

[[0.24266547 0.         0.         0.         0.         0.
  0.         0.24266547 0.         0.         0.40286636 0.
  0.         0.         0.         0.24266547 0.11527033 0.24266547
  0.         0.         0.         0.         0.72799642 0.
  0.         0.24266547 0.         0.        ]
 [0.         0.         0.         0.         0.30652086 0.5680354
  0.         0.         0.         0.         0.         0.
  0.         0.         0.5680354  0.         0.26982671 0.
  0.         0.         0.30652086 0.         0.         0.
  0.         0.         0.30652086 0.        ]]

In [13]:
import pandas as pd

df = pd.read_csv('Data Files/Ecommerce_data.csv')

print(df.info(),'\n\n',df.describe())

print(df.head())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 24000 entries, 0 to 23999
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Text    24000 non-null  object
 1   label   24000 non-null  object
dtypes: object(2)
memory usage: 375.1+ KB
None

                                                      Text      label
count                                               24000      24000
unique                                              13834          4
top     Diverse Men's Formal Shirt Diverse is a wester...  Household
freq                                                   23       6000
                                                Text                   label
0  Urban Ladder Eisner Low Back Study-Office Comp...               Household
1  Contrast living Wooden Decorative Box,Painted ...               Household
2  IO Crest SY-PCI40010 PCI RAID Host Controller ...             Electronics
3  ISAKAA Baby Socks from Just Born to 8 Years- P...  Clothing & Accessories
4  Indira Designer Women's Art Mysore Silk Saree ...  Clothing & Accessories

In [14]:
df['label'].value_counts()

label
Household                 6000
Electronics               6000
Clothing & Accessories    6000
Books                     6000
Name: count, dtype: int64

In [15]:
df['target'] = df['label'].map({
    'Household' : 0,
    'Electronics' : 1,
    'Clothing & Accessories' : 2,
    'Books' : 3
})

df.head()

,Text,label,target
0,Urban Ladder Eisner Low Back Study-Office Comp...,Household,0
1,"Contrast living Wooden Decorative Box,Painted ...",Household,0
2,IO Crest SY-PCI40010 PCI RAID Host Controller ...,Electronics,1
3,ISAKAA Baby Socks from Just Born to 8 Years- P...,Clothing & Accessories,2
4,Indira Designer Women's Art Mysore Silk Saree ...,Clothing & Accessories,2

In [16]:
df['target'].value_counts()

target
0    6000
1    6000
2    6000
3    6000
Name: count, dtype: int64

In [17]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(df['Text'],df['target'], test_size=0.2,random_state=2024,stratify=df['target'])
print(X_test.shape,y_train.shape)

(4800,) (19200,)

In [11]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import classification_report
from sklearn.pipeline import Pipeline
from sklearn.ensemble import RandomForestClassifier

In [19]:
p1 = Pipeline([
    ('vectorizer',TfidfVectorizer()),
    ('knn',KNeighborsClassifier())
])

p2 = Pipeline([
    ('vectorizer',TfidfVectorizer()),
    ('rf',RandomForestClassifier(n_estimators=15))
])

p3 = Pipeline([
    ('vectorizer',TfidfVectorizer()),
    ('nb',MultinomialNB())
])

p1.fit(X_train,y_train)
p2.fit(X_train,y_train)
p3.fit(X_train,y_train)

print('Classification For KNN\n')
print(classification_report(y_test,p1.predict(X_test)))

print('Classification For RF\n')
print(classification_report(y_test,p2.predict(X_test)))

print('Classification For NB\n')
print(classification_report(y_test,p3.predict(X_test)))

Classification For KNN

              precision    recall  f1-score   support

           0       0.96      0.96      0.96      1200
           1       0.97      0.97      0.97      1200
           2       0.98      0.98      0.98      1200
           3       0.97      0.96      0.96      1200

    accuracy                           0.97      4800
   macro avg       0.97      0.97      0.97      4800
weighted avg       0.97      0.97      0.97      4800

Classification For RF

              precision    recall  f1-score   support

           0       0.94      0.96      0.95      1200
           1       0.98      0.94      0.96      1200
           2       0.98      0.98      0.98      1200
           3       0.97      0.98      0.98      1200

    accuracy                           0.97      4800
   macro avg       0.97      0.97      0.97      4800
weighted avg       0.97      0.97      0.97      4800

Classification For NB

              precision    recall  f1-score   support

           0       0.93      0.97      0.95      1200
           1       0.97      0.96      0.97      1200
           2       0.98      0.98      0.98      1200
           3       0.98      0.95      0.97      1200

    accuracy                           0.97      4800
   macro avg       0.97      0.97      0.97      4800
weighted avg       0.97      0.97      0.97      4800

In [18]:
import spacy

nlp = spacy.load('en_core_web_sm')

def preprocess(text):
    filtered_tokens = []
    doc = nlp(text)

    for token in doc:
        if token.is_stop or token.is_punct:
            continue
        filtered_tokens.append(token.lemma_)
    return " ".join(filtered_tokens)

In [21]:
df['preprocessed'] = df['Text'].apply(preprocess)

In [22]:
df.head()

,Text,label,target,preprocessed
0,Urban Ladder Eisner Low Back Study-Office Comp...,Household,0,Urban Ladder Eisner Low Study Office Computer ...
1,"Contrast living Wooden Decorative Box,Painted ...",Household,0,contrast live Wooden Decorative Box Painted Bo...
2,IO Crest SY-PCI40010 PCI RAID Host Controller ...,Electronics,1,IO Crest SY PCI40010 PCI RAID Host Controller ...
3,ISAKAA Baby Socks from Just Born to 8 Years- P...,Clothing & Accessories,2,ISAKAA Baby Socks bear 8 Years- Pack 4 6 8 12 ...
4,Indira Designer Women's Art Mysore Silk Saree ...,Clothing & Accessories,2,Indira Designer woman Art Mysore Silk Saree Bl...

In [23]:
X_train, X_test, y_train, y_test = train_test_split(df['preprocessed'],df['target'], test_size=0.2,random_state=2024,stratify=df['target'])
print(X_test.shape,y_train.shape)

(4800,) (19200,)

In [24]:
p1.fit(X_train,y_train)
p2.fit(X_train,y_train)
p3.fit(X_train,y_train)

print('Classification For KNN\n')
print(classification_report(y_test,p1.predict(X_test)))

print('Classification For RF\n')
print(classification_report(y_test,p2.predict(X_test)))

print('Classification For NB\n')
print(classification_report(y_test,p3.predict(X_test)))

Classification For KNN

              precision    recall  f1-score   support

           0       0.95      0.96      0.96      1200
           1       0.96      0.97      0.97      1200
           2       0.99      0.98      0.98      1200
           3       0.97      0.96      0.96      1200

    accuracy                           0.97      4800
   macro avg       0.97      0.97      0.97      4800
weighted avg       0.97      0.97      0.97      4800

Classification For RF

              precision    recall  f1-score   support

           0       0.95      0.96      0.96      1200
           1       0.98      0.95      0.97      1200
           2       0.98      0.98      0.98      1200
           3       0.97      0.98      0.98      1200

    accuracy                           0.97      4800
   macro avg       0.97      0.97      0.97      4800
weighted avg       0.97      0.97      0.97      4800

Classification For NB

              precision    recall  f1-score   support

           0       0.94      0.97      0.96      1200
           1       0.97      0.97      0.97      1200
           2       0.98      0.99      0.99      1200
           3       0.99      0.95      0.97      1200

    accuracy                           0.97      4800
   macro avg       0.97      0.97      0.97      4800
weighted avg       0.97      0.97      0.97      4800

### Exercise

In [2]:
import pandas as pd

df = pd.read_csv('Data Files/Emotion_classify_Data.csv')

print(df.shape)
print(df.info(),'\n\n',df.describe())
df.head()

(5937, 2)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5937 entries, 0 to 5936
Data columns (total 2 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Comment  5937 non-null   object
 1   Emotion  5937 non-null   object
dtypes: object(2)
memory usage: 92.9+ KB
None

                                                  Comment Emotion
count                                               5937    5937
unique                                              5934       3
top     i feel like a tortured artist when i talk to her   anger
freq                                                   2    2000

                                             Comment Emotion
0  i seriously hate one subject to death but now ...    fear
1                 im so full of life i feel appalled   anger
2  i sit here to write i start to dig out my feel...    fear
3  ive been really angry with r and i feel like a...     joy
4  i feel suspicious if there is no one outside l...    fear

In [3]:
df['Emotion'].value_counts()

Emotion
anger    2000
joy      2000
fear     1937
Name: count, dtype: int64

In [4]:
df['target'] = df['Emotion'].map({
    'joy' : 0,
    'fear' : 1,
    'anger' : 2
})

df.head()

                                             Comment Emotion  target
0  i seriously hate one subject to death but now ...    fear       1
1                 im so full of life i feel appalled   anger       2
2  i sit here to write i start to dig out my feel...    fear       1
3  ive been really angry with r and i feel like a...     joy       0
4  i feel suspicious if there is no one outside l...    fear       1

### Modelling without Preprocessing

In [6]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(df['Comment'],df['target'], test_size=0.2,random_state=2024,stratify=df['target'])

In [7]:
print(X_train.shape,X_test.shape)

(4749,) (1188,)

In [8]:
from sklearn.feature_extraction.text import CountVectorizer

### Attempt 1
- CountVectorizer with only trigrams
- RF as classifier

In [12]:
from sklearn.pipeline import Pipeline

p1 = Pipeline([
    ('vectorizer',CountVectorizer(ngram_range=(3,3))),
    ('rf',RandomForestClassifier(n_estimators=20))
])

p1.fit(X_train,y_train)

print(classification_report(y_test,p1.predict(X_test)))

              precision    recall  f1-score   support

           0       0.56      0.22      0.32       400
           1       0.60      0.46      0.52       388
           2       0.41      0.75      0.53       400

    accuracy                           0.48      1188
   macro avg       0.52      0.48      0.46      1188
weighted avg       0.52      0.48      0.46      1188

### Attempt 2
- CV for uni and bigrams
- NB as classifier

In [13]:
p2 = Pipeline([
    ('vectorizer',CountVectorizer(ngram_range=(1,2))),
    ('rf',MultinomialNB())
])

p2.fit(X_train,y_train)

print(classification_report(y_test,p2.predict(X_test)))

              precision    recall  f1-score   support

           0       0.89      0.86      0.88       400
           1       0.86      0.87      0.87       388
           2       0.86      0.88      0.87       400

    accuracy                           0.87      1188
   macro avg       0.87      0.87      0.87      1188
weighted avg       0.87      0.87      0.87      1188

### Attempt 3
- CV with uni and bigrams
- RF as classifier

In [14]:
p3 = Pipeline([
    ('vectorizer',CountVectorizer(ngram_range=(1,2))),
    ('rf',RandomForestClassifier(n_estimators=20))
])

p3.fit(X_train,y_train)

print(classification_report(y_test,p3.predict(X_test)))

              precision    recall  f1-score   support

           0       0.79      0.95      0.87       400
           1       0.91      0.82      0.86       388
           2       0.94      0.85      0.89       400

    accuracy                           0.87      1188
   macro avg       0.88      0.87      0.87      1188
weighted avg       0.88      0.87      0.87      1188

### Attempt 4
- TF-IDF
- RF

In [16]:
from sklearn.feature_extraction.text import TfidfVectorizer

p4 = Pipeline([
    ('vectorizer',TfidfVectorizer()),
    ('rf',RandomForestClassifier(n_estimators=20))
])

p4.fit(X_train,y_train)

print(classification_report(y_test,p4.predict(X_test)))

              precision    recall  f1-score   support

           0       0.82      0.89      0.85       400
           1       0.87      0.87      0.87       388
           2       0.90      0.82      0.86       400

    accuracy                           0.86      1188
   macro avg       0.86      0.86      0.86      1188
weighted avg       0.86      0.86      0.86      1188

### Using Text Preprocessing

In [19]:
df['preprocessed'] = df['Comment'].apply(preprocess)
df.head()

,Comment,Emotion,target,preprocessed
0,i seriously hate one subject to death but now ...,fear,1,seriously hate subject death feel reluctant drop
1,im so full of life i feel appalled,anger,2,m life feel appalled
2,i sit here to write i start to dig out my feel...,fear,1,sit write start dig feeling think afraid accep...
3,ive been really angry with r and i feel like a...,joy,0,ve angry r feel like idiot trust place
4,i feel suspicious if there is no one outside l...,fear,1,feel suspicious outside like rapture happen

In [20]:
X_train, X_test, y_train, y_test = train_test_split(df['preprocessed'],df['target'], test_size=0.2,random_state=2024,stratify=df['target'])

### Attempt 1
- CV for (1,2)
- RF as classifier

In [21]:
p_pre_1 = Pipeline([
    ('vectorizer',CountVectorizer(ngram_range=(1,2))),
    ('rf',RandomForestClassifier(n_estimators=20))
])

p_pre_1.fit(X_train,y_train)

print(classification_report(y_test,p_pre_1.predict(X_test)))

              precision    recall  f1-score   support

           0       0.91      0.94      0.92       400
           1       0.91      0.91      0.91       388
           2       0.93      0.91      0.92       400

    accuracy                           0.92      1188
   macro avg       0.92      0.92      0.92      1188
weighted avg       0.92      0.92      0.92      1188

### Attempt 2
- TF-IDF
- RF

In [22]:
p_pre_2 = Pipeline([
    ('vectorizer',TfidfVectorizer()),
    ('rf',RandomForestClassifier(n_estimators=20))
])

p_pre_2.fit(X_train,y_train)

print(classification_report(y_test,p_pre_2.predict(X_test)))

              precision    recall  f1-score   support

           0       0.90      0.95      0.92       400
           1       0.90      0.93      0.91       388
           2       0.94      0.85      0.90       400

    accuracy                           0.91      1188
   macro avg       0.91      0.91      0.91      1188
weighted avg       0.91      0.91      0.91      1188